<?php
/**
 * MessagesApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.10.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for binarySendPost
     *
     * Send a binary SMS message.
     *
     */
    public function testBinarySendPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messageFlashPost
     *
     * .
     *
     */
    public function testMessageFlashPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messageSchedulePost
     *
     * Schedule an SMS message.
     *
     */
    public function testMessageSchedulePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messageSendPost
     *
     * .
     *
     */
    public function testMessageSendPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesFailedPost
     *
     * .
     *
     */
    public function testMessagesFailedPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesInboxPost
     *
     * Retrieve unread uncoming messages.
     *
     */
    public function testMessagesInboxPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesMessageidDelete
     *
     * .
     *
     */
    public function testMessagesMessageidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesMessageidGet
     *
     * Get message by messageid.
     *
     */
    public function testMessagesMessageidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesPost
     *
     * Get messages matching your criteria.
     *
     */
    public function testMessagesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesScheduleGet
     *
     * Retrieve scheduled messages.
     *
     */
    public function testMessagesScheduleGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesScheduleMessageidDelete
     *
     * Cancel scheduled SMS message.
     *
     */
    public function testMessagesScheduleMessageidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for messagesVolumeGet
     *
     * Volume of messages sent since midnight.
     *
     */
    public function testMessagesVolumeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
